spring.application.name=mybriefmarkensammlung


server.tomcat.max-part-count=100
server.tomcat.max-part-header-size=8KB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-parameter-count=1000
server.tomcat.max-http-form-post-size=-1

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.platform=postgresql